#!/bin/sh

#Sample
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/Sample/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'

# Include
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/Include/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'

#Linux_BSP
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/Linux_BSP/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'

#NvpDle
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/NvpDle/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'

#NvpMedia
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/NvpMedia/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/NvpMedia/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'

#Shared
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#\t#    #g'   
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#while(#while (#g'                                 
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#for(#for (#g'       
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#if(#if (#g'        
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#switch(#switch (#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#\([a-zA-Z0-9;:{ \t]\)//#\1  //#g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's#//\([a-zA-Z0-9;:{ \t]=\)#//  \1#g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's#//#  //  #g'    
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/[ \t]*$//g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)=/\1 =/g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/=\([a-zA-Z0-9]\)/= \1/g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\),/\1 ,/g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/,\([a-zA-Z0-9]\)/, \1/g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/>\([a-zA-Z0-9]\)/> \1/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/\([a-zA-Z0-9]\)>/\1 >/g'
#find NVPSDK/Sample/ -name "*.cpp" | xargs sed -i 's/<\([a-zA-Z0-9]\)/< \1/g'
find NVPSDK/Shared/ -name "*.cpp" -o -name "*.h" -o -name "*.c" | xargs sed -i 's/\([a-zA-Z0-9]\)</\1 </g'